version: '3.8'

services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.2
    container_name: cockroachdb
    command: start-single-node --insecure --advertise-addr=cockroachdb
    ports:
      - '26257:26257' # Cổng dành cho client
      - '8080:8080' # Cổng dành cho giao diện web (Admin UI)
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data
    networks:
      - cockroach-network

volumes:
  cockroachdb-data:

networks:
  cockroach-network:
    driver: bridge
